experiment:
  name: svd_eps1e-3_tile32x128x128
  output_dir: results/

dataset:
  version: "500"
  dtype: "float32"

tiledb:
  codec: "zstd"
  level: 7
  tile: [32, 128, 128]
  overwrite: true

semantic_compression:
  algorithm: "svd"
  rank: 20          # r值 for SVD
  epsilon: 1e-3     # 误差约束
  # 若使用 randomized SVD:
  #   algorithm: "rsvd"
  #   oversampling: 10
  #   n_iter: 2
  # 若使用 Tucker/HOSVD:
  #   algorithm: "tucker"
  #   ranks: [20, 40, 40]

evaluation:
  metrics: ["compression_ratio", "mse", "psnr"]
